<?php

/**
 * Cms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    demo1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cms extends BaseCms
{
  
  public function getTitleWithId()
  {
    return $this->title.'('.$this->id.')';
  }
  
}
