<?php

/**
 * CmsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cms');
    }
    
    public function retrieveBySlug($options = array())
    {
      
      if (!isset($options['slug']))
      {
        throw new InvalidArgumentException('The slug is required in the options');
      }
      
      return $this->createQuery('c')
            ->where('slug = ?', $options['slug'])->fetchOne();
      
    }    
}