cms:
  class: sfDoctrineRouteCollection
  options:
    model:                Cms
    module:               CmsAdmin
    prefix_path:          /CmsAdmin
    column:               id
    with_wildcard_routes: true

product_Product:
  class: sfDoctrineRouteCollection
  options:
    model:                Product
    module:               Product
    prefix_path:          /Product
    column:               id
    with_wildcard_routes: true

product:
  class: sfDoctrineRouteCollection
  options:
    model:                Product
    module:               ProductAdmin
    prefix_path:          /ProductAdmin
    column:               id
    with_wildcard_routes: true

category:
  class: sfDoctrineRouteCollection
  options:
    model:                Category
    module:               CategoryAdmin
    prefix_path:          /CategoryAdmin
    column:               id
    with_wildcard_routes: true


cms_slug:
  url:   /:slug
  class: cmsDoctrineRoute
  options: { model: Cms, type: object, method: retrieveBySlug }
  param: { module: cms, action: show }
  requirements:  
    slug: (?:[^?]*) 
    sf_method: [post, get]     

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
