generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MailQueue
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          mail_queue
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [id, subject, message, from_mail, to_email, inprogress, sended, system, created_at]
      filter:  ~
      form:    ~
      edit:    
      new:     
      
