Product:
  actAs:
    Sluggable:
      fields: [title]
      name: slug    
      type: string  
      length: 255   
      unique: true
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true  
    title: 
      type: string(60)
      notnull: true
    description: 
      type: text
    category_id:
      type: integer(11)
  relations:
    Category:
      foreignAlias: Products
      class: Category
                
Category:
  actAs:
    Sluggable:
      fields: [title]
      name: slug    
      type: string  
      length: 255   
      unique: false
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true  
    title: 
      type: string(60)
      notnull: true
    description: 
      type: text
      notnull: true
      
                
Cms:
  actAs:
    Sluggable:
      fields: [title]
      name: slug    
      type: string  
      length: 255   
      unique: true
    NestedSet: 
      hasManyRoots: true
      rootColumnName: root_id      
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true  
    title: 
      type: string(60)
      notnull: true
    description: 
      type: text
      notnull: true
    is_module:  
      type: boolean
      default: false
    route:
      type: string(200)
      notnull: false
    content: 
      type: blob
      notnull: false
    